plezanje-net/web

src/app/pages/crag/crag-by-slug.query.graphql
src/app/pages/crag/crag-image/crag-image.component.html
src/app/pages/crag/crag-image/crag-image.component.scss
src/app/pages/crag/crag-location/crag-location.component.html
src/app/pages/crag/crag-location/crag-location.component.scss
src/app/pages/crags/crags.component.html
src/app/shared/pipes/orientation.pipe.ts
src/app/shared/shared.module.ts
src/generated/graphql.ts

- orientation pipe
- put location stuff into card similar to route view

Crag location refinement

---

src/app/pages/crag/crag.component.ts
src/app/pages/crags/crags.component.ts

added error handler to observer of cragsgql

---

src/app/app.component.html
src/app/app.component.scss
src/app/app.component.ts
src/index.html

also added auto year update in copyright. :)
closes #55

pushed footer to bottom on short pages.

---

src/app/common/comment/comment.component.html
src/app/common/comment/comment.component.ts
src/app/graphql/graphql.module.ts
src/app/pages/crag/crag-by-slug.query.graphql
src/app/pages/crag/crag-comments/crag-comments.component.html
src/app/pages/crag/crag-comments/crag-comments.component.ts
src/app/pages/crag/crag-warnings/crag-warnings.component.html
src/app/pages/crag/crag-warnings/crag-warnings.component.ts
src/generated/graphql.ts

Join comment resolvers

---

src/app/layout/header/header.component.html
src/app/pages/crag/crag.component.html
src/app/pages/crag/crag.component.ts

Crag location display, default to sport routes

---

src/app/pages/crags/crags.component.ts

Added regex to disregard čćšž accents on crag list search.

---

src/app/pages/crag/crag-routes/crag-routes.component.ts

Description in issue https://github.com/plezanje-net/web/issues/95

#95 Remove snack bar for activity log after user leaves crag page

---

src/app/common/distribution-chart/distribution-chart.component.html
src/app/common/distribution-chart/distribution-chart.component.scss
src/app/pages/crag/crag-by-slug.query.graphql
src/app/pages/crag/crag-location/crag-location.component.html
src/app/pages/crag/crag-location/crag-location.component.ts

Note that I took a stab at the distribution chart global component, which needs a bit of designer love on both route and crag page.

Crag attendance by month distribution chart

---

src/app/common/grade/grade.component.ts
src/app/forms/activity-form/activity-form-route/activity-form-route.component.html
src/app/forms/activity-form/activity-form-route/activity-form-route.component.ts
src/app/forms/activity-form/activity-form.component.ts
src/app/pages/crag/crag-by-slug.query.graphql
src/app/pages/crag/crag-routes/crag-routes.component.html
src/app/pages/route/route-info/route-info.component.html
src/app/pages/route/route.query.graphql
src/app/pages/search/search-results/search-results.component.html
src/app/pages/search/search.query.graphql

Show P instead of grade for projects.
When a project is ticked make voting on grade required.
closes #102 
To test check all views that show route grade.

Show p for project

---

src/app/common/grade/grade.component.html
src/app/common/grade/grade.component.scss
src/app/pages/crag/crag-routes/crag-routes.component.html
src/app/shared/services/grading-systems.service.ts

Fix wrapping of modifier on crag page and small screens.
Test by going to crag page of a crag that has some routes with modifiers. Resize browser window.
closes #120

Fix grade modifier layout.

---

src/app/app.component.ts
src/app/auth/auth.guard.ts
src/app/auth/auth.service.ts
src/app/auth/login/login.component.html
src/app/auth/login/login.component.ts
src/app/layout/header/header.component.html
src/app/layout/header/header.component.ts
src/app/pages/crag/crag.component.ts

Test this by logging in and see the navbar links change. then logout directly from navbar menu.
closes #97

Navbar modification - login state

---

src/app/auth/auth.service.ts
src/app/management/forms/crag-form/crag-form.component.ts
src/app/management/pages/crag/crag.component.ts
src/app/pages/activity/activity-log/activity-log.component.ts
src/app/pages/activity/activity-routes/activity-routes.component.ts
src/app/pages/club/club-activity-routes/club-activity-routes.component.ts
src/app/pages/home/exposed-warnings/expsoed-warnings.component.ts
src/app/pages/home/latest-images/latest-images.component.ts
src/app/pages/home/latest-ticks/latest-ticks.component.ts
src/app/pages/home/popular-crags/popular-crags-card/popular-crags-card.component.ts
src/app/pages/search/search.component.ts
src/app/shared/services/grading-systems.service.ts

One toPromise is left in comments component because there is another bug there and cannot test...

Replace all occurences of toPromise()

---

src/app/common/grade-distribution.ts
src/app/pages/route/route-info/route-info.component.ts

Moves code to common place for later use
Also fixes bug where all grades had the same count (1)

Move grade distribution creation to common util function

---

src/app/app.component.ts
src/app/app.module.ts
src/app/auth/auth-interceptor.ts
src/app/auth/auth.guard.ts
src/app/auth/auth.service.ts
src/app/auth/login/login.component.html
src/app/auth/login/login.component.ts
src/app/auth/login/login.mutation.graphql
src/app/auth/password-recovery/password-recovery.component.html
src/app/layout/header/header.component.html
src/app/layout/header/header.component.ts
src/app/pages/account/register/register.component.html
src/app/pages/club/club-members/club-members.component.html
src/app/pages/club/club-members/club-members.component.ts
src/app/pages/club/club.service.ts
src/app/pages/crag/crag-routes/crag-routes.component.ts
src/app/pages/crag/crag.component.ts
src/app/shared/components/comment/comment.component.ts
src/app/shared/components/warnings/warnings.component.html
src/app/shared/components/warnings/warnings.component.ts
src/app/shared/shared.module.ts

Test this with the corresponding backend PR:
https://github.com/plezanje-net/api/pull/50
- run migration and codegen
- logout and open crag where you have some ascents logged
- login and see that the ticks appear (current user observable works)
- either change your password in another browser, set isActive to false for your account in DB or rename your "admin" role in DB to something else
- navigate anywhere on the page or reload the crag view and you should be logged out and redirected to home page
closes #138 
closes #136

Auth rework - currentUser to observable, token expiration interceptor

---

src/app/app.module.ts
src/app/pages/crag/crag-by-slug.query.graphql
src/app/shared/components/comment-form/comment-form.component.html
src/app/shared/components/comment-form/comment-form.component.scss
src/app/shared/components/comment-form/comment-form.component.ts
src/app/shared/shared.module.ts

Add exposedUntil date field to warning forms.
Test this by adding a new warning and set the exposedUntil date on the warning form. 
Then go to home and see that the warning is exposed.
Also try editing such comment.
closes #84

Warnings exposedUntil field

---

src/app/pages/activity/activity-entry/activity-entry.component.html
src/app/pages/activity/activity-entry/activity-entry.component.ts
src/app/pages/activity/activity-entry/activity-entry.query.graphql
src/app/pages/activity/partials/activity-route-row/activity-route-row.component.html

Activity day was not working because route difficulties were not queried.
Also add some of the missing row actions.
Test by going to log, and click on 'odpri plezalni dan'

Fix activity day

---

src/app/forms/activity-form/activity-form.component.ts
src/app/management/utils/crag-admin-breadcrumbs.ts
src/app/pages/crag/crag-routes/crag-routes.component.html
src/app/pages/home/exposed-warnings/exposed-warnings.component.html
src/app/pages/route/route.component.ts

open crag and click on a route

Fix links to routes

---

src/app/app.module.ts
src/app/pages/account/confirm-account/confirm-account.component.html
src/app/pages/account/register/register.component.html
src/app/pages/account/register/register.component.scss
src/app/pages/account/register/register.component.ts
src/app/pages/account/register/register.mutation.graphql

Chrome was so 'smart' that it treated some registration form fields as password fields although they were not. 
This PR adds some attributes that makes it clear to 'it'.
Registration form was missing gender field. 
This PR adds it.
There was a slight layout problem with registration form which this PR also fixes.
Some messages in the registration process still used viking instead of tiking. Also fixed with this PR.
Test this with API PR plezanje-net/api#74
To test try registering as a new user and observe all of the above.
Also resize browser window to check layout on different screen sizes.
resolves #183 
resolves #192

Registration form fix

---

src/app/pages/crag/crag.component.ts

This PR actually does not fix the issue, but does make displaying the error right.
The issue is fixed by API PR plezanje-net/api#75
Test by opening Paklenica crag.

Crag fail fix

---

src/app/activity/forms/activity-form/activity-form-route/activity-form-route.component.html
src/app/activity/forms/activity-form/activity-form-route/activity-form-route.component.scss
src/app/activity/forms/activity-form/activity-form.component.ts

Voting on route 'beauty' aka star rating voting is now compliant with latest discussions. 
Only 0, 1, 2 stars can be given, or no vote at all.
To test log some routes. Test with plezanje-net/api#90

Star rating vote on log form.

---

src/app/app.component.ts
src/app/pages/crag/crag-info/crag-info.component.ts
src/app/pages/crag/crag.component.ts
src/app/pages/crags/crags.component.ts
src/app/pages/home/home.component.ts
src/app/pages/route/route.component.ts
src/app/services/layout.service.ts
src/index.html

Closes #250 
Closes https://github.com/plezanje-net/web/issues/266

Seo improvements 250

---

src/app/app-routing.module.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/pages/about/about.component.html
src/app/pages/about/about.component.spec.ts
src/app/pages/about/about.component.ts

Adds a simple about page with the first version of the texts

About page

---

src/app/pages/about/about.component.html
src/app/pages/about/about.component.scss
src/app/pages/home/home.component.html
src/app/pages/home/home.component.scss
src/styles/global.scss

Adds a card with "welcome" text to the home page and added some fixes to the about page.

About page text improvements

---

src/app/pages/home/latest-ticks/latest-ticks.component.scss
src/app/pages/home/latest-ticks/latest-ticks.component.ts

Display latest n ticks on homepage (instead of last n days).

---

src/app/pages/route/route-info/route-info.component.html
src/app/pages/route/route-info/route-info.component.ts
src/app/pages/route/route.query.graphql

Route authors are now displayed according to routevents, not parsed from "eventcache".
Test with: https://github.com/plezanje-net/api/pull/93
Compare local and deployed:
https://plezanje.net/plezalisce/pod-skalo/smer/mcchicken
http://localhost:4200/plezalisce/pod-skalo/smer/mcchicken

Route events

---

src/app/activity/forms/activity-form/activity-form.component.html

Temporarily disable option to log routes without day. 

---

src/app/activity/forms/activity-form/activity-form.component.ts
src/app/activity/forms/activity-form/create-activity-routes.mutation.graphql

test with https://github.com/plezanje-net/api/pull/94 and see that no activities are created when saving only routes

create activity routes only

---

src/app/activity/forms/activity-form/activity-form-route/activity-form-route.component.html
src/app/activity/pages/activity-entry/activity-entry.component.html
src/app/activity/pages/activity-routes/activity-routes.component.html
src/app/activity/pages/activity-routes/activity-routes.component.ts
src/app/activity/partials/activity-route-row/activity-route-change-publish.graphql
src/app/activity/partials/activity-route-row/activity-route-row.component.html
src/app/activity/partials/activity-route-row/activity-route-row.component.ts

test with https://github.com/plezanje-net/api/pull/95
go to your logged routes and change visibility from the menu

Change activity route publish

---

src/app/activity/pages/activity-log/activity-log.component.html
src/app/activity/pages/activity-log/activity-log.component.ts
src/app/activity/pages/activity-routes/activity-routes.component.html
src/app/app.module.ts
src/app/common/filtered-table.ts
src/app/pages/club/club-activity-routes/club-activity-routes.component.html

Create entry into climbing log and see that the manual entry gets validated propertly, try out the date range picker on both lists and see that it works. Date range picker placeholder is now in slovenian and weeks start with monday

Fix datepicker

---

src/app/pages/home/home.component.html

open homepage and see the text around the link to the archive pnet page. 
open to suggestions.

Add link to old plezanje.net page to home page banner.

---

src/app/activity/pages/activity-log/activity-log.component.html
src/app/activity/pages/activity-routes/activity-routes.component.html
src/app/pages/club/club-activity-routes/club-activity-routes.component.html

Makes date range inputs readonly do they are now only usable with the calendar popup. 
This does not affect individual date inputs.
Closes #312

Date range input

---

src/app/activity/forms/activity-form/activity-form.component.html
src/app/activity/forms/activity-form/activity-form.component.ts

Test api first> https://github.com/plezanje-net/api/pull/112
Then test this by logging a route. observe that all future dates are disabled.
closes #339

Disable future dates in activity date datepicker.

---

src/app/management/forms/route-form/route-form.component.ts

To test:
Try adding a route, enter length see that it works now.
Also try editing a route's length and see that it works now.

Fix length type mismatch on route add/edit form.

---

src/app/pages/home/home.component.html

Remove exposed news from changelog.

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/pages/home/home.component.html
src/app/pages/home/latest-difficulty-votes/latest-difficulty-votes.component.html
src/app/pages/home/latest-difficulty-votes/latest-difficulty-votes.component.scss
src/app/pages/home/latest-difficulty-votes/latest-difficulty-votes.component.spec.ts
src/app/pages/home/latest-difficulty-votes/latest-difficulty-votes.component.ts
src/app/pages/home/latest-difficulty-votes/latest-difficulty-votes.query.graphql
src/app/statistics/pages/difficulty-votes/difficulty-votes.component.html
src/app/statistics/pages/difficulty-votes/difficulty-votes.component.scss
src/app/statistics/pages/difficulty-votes/difficulty-votes.component.spec.ts
src/app/statistics/pages/difficulty-votes/difficulty-votes.component.ts
src/app/statistics/pages/difficulty-votes/difficulty-votes.query.graphql
src/app/statistics/pages/statistics-home/statistics-home.component.html
src/app/statistics/pages/statistics-home/statistics-home.component.spec.ts
src/app/statistics/pages/statistics-home/statistics-home.component.ts
src/app/statistics/statistics-routing.module.ts
src/app/statistics/statistics.module.ts

Adds widget to home page that displays last 10 difficulty votes and a link to internal page listing all of them paginated. 
The home page widget has only narrow view intentionally, I think it would be best grouped side by side with some other widget.
See how it switches from table to mobile view on the internal page

Latest difficulty votes

---

src/app/app.module.ts
src/app/pages/home/home.component.html
src/app/pages/home/latest-comments/latest-comments.component.html
src/app/pages/home/latest-comments/latest-comments.component.scss
src/app/pages/home/latest-comments/latest-comments.component.spec.ts
src/app/pages/home/latest-comments/latest-comments.component.ts
src/app/pages/home/latest-comments/latest-comments.query.graphql
src/app/pages/home/latest-difficulty-votes/latest-difficulty-votes.component.ts
src/app/shared/components/comment/comment-options/comment-options.component.ts
src/app/shared/components/comment/comment.component.html
src/app/shared/components/comment/comment.component.scss
src/app/shared/components/comment/comment.component.ts
src/app/statistics/pages/comments-history/comments-history.component.html
src/app/statistics/pages/comments-history/comments-history.component.scss
src/app/statistics/pages/comments-history/comments-history.component.spec.ts
src/app/statistics/pages/comments-history/comments-history.component.ts
src/app/statistics/statistics-routing.module.ts
src/app/statistics/statistics.module.ts

#356 
This PR adds a list of latest comments to the home page and it adds page "/pregledi/komentarji" to the statistics pages similar to the ones for ascents and difficulty votes.
Please test together with the matching API PR https://github.com/plezanje-net/api/pull/147
**Example of new component on home page:**
**Comments history page:**

#356 Latest comments

---

src/app/pages/home/latest-ascents/latest-ascents.component.ts
src/app/shared/components/ascents/ascents.component.html
src/app/shared/components/ascents/ascents.query.graphql
src/app/statistics/pages/ascents-history/ascents-history.component.ts

Uses new scoring fields on latest ascents view and on log view.
test with https://github.com/plezanje-net/api/pull/157

Fix scoring.

---

src/app/activity/pages/activity-statistics/activity-statistics.component.html
src/app/activity/pages/activity-statistics/activity-statistics.component.ts

Fixes #454
Rewrite component and html to avoid resorting on scroll.

Table with statistics is sorting on scroll

---

src/app/activity/pages/activity-statistics/activity-statistics.component.ts

There was a bug in statistics where all types of routes were considered as sport in tables and graphs. This PR adds a hardcoded filter to the query. The backend implementation allows us to add  filters to the frontend for an upgrade of this, to also have alpine / bouldering statistics.
Test by adding a high grade boulder to your log and see that it is counted as a route in statistics (8a boulder as 8b+ route). Then apply [the API PR](https://github.com/plezanje-net/api/pull/171), run codegen, apply this and open stats again.

Statistics - count only sport routes

---

src/app/activity/pages/activity-statistics/activity-statistics.component.html
src/app/activity/pages/activity-statistics/activity-statistics.component.ts
src/app/activity/pages/activity-statistics/activity-statistics.query.graphql
src/app/common/activity.constants.ts
src/app/types/ascent-type.ts

- added all ascent types to route statistics
- added chart activities by year

Additional features for statistics tab
