src/app/common/ascent-type/ascent-type.component.html, src/app/pages/crag/crag-routes/crag-routes.component.html, src/app/pages/crag/crag-routes/crag-routes.component.scss, src/styles/variables.scss
This PR makes changes to crag routes rows. The route rows now wrap into two rows on mobile and the icons stay aligned to the right edge. I know that this isn't perfect but it's better than before. Hopefully the designer will have a better idea.
I also replaced `flex-layout` properties because the rendering of the bigger tables (e.g.: Osp, Kotečnik) was pretty slow. I suggest we minimise use of the library in tables.
**Desktop size example. Not very different.**
**Mobile size:**
=> Crag routes responsive layout

src/app/common/map/map.component.ts, src/app/pages/crag/crag-routes/crag-routes.component.ts
Added some padding when fitting markers. For some reason just `size: this.map.getSize(),` is not enough.
Another thing: fixing when user is logged in and visits page for a specific crag. Then he logs out, and is redirected to ˙/˙, but `myCragSummaryGQL` subscription is still triggered. Because use is now logged out, `data` property is `null`. This results in null reference exception.
Closes #66
=> Fix fit 2 markers on the map

src/app/graphql/graphql.module.ts
Apollo cached Crag objects but did not consider that nrRoutes can change according to query parameters. 
The nrRoutes field was added to cache key calculation.
=> Route count as cache key

src/app/graphql/graphql.module.ts
Reverts plezanje-net/web#98
just realized that crag page does not work after this change...
getting error: 'Invariant Violation: Missing field 'nrRoutes' while extracting keyFields from...'
=> Revert "Route count as cache key"

src/app/common/grade/grade.component.html, src/app/common/grade/grade.component.ts, src/app/shared/services/grading-systems.query.graphql, src/app/shared/services/grading-systems.service.spec.ts, src/app/shared/services/grading-systems.service.ts
This PR adds service `GradingSystemsService` which will be used to convert between grades and difficulties based on provided grading system.
I implemented method `diffToGrade` which returns the appropriate grade name and modifier for the provided difficulty. It can also convert to legacy grades but only if the provided difficulty is "accurate" (400, 425, 450 ...).
I think it should work for all grading systems because it loops over the array of grades instead of doing arithmetics. But I didn't test other than french yet because I want to confirm that this is the way to go first before I put in more time.
I noticed that this service converts diffs to grades differently than the Grade class but I think that this is accurate now.
**Example using `Grade.ts` class:**
**Example using …
=> Add service for converting diff to grade based on grading system

src/app/pages/search/search.component.ts
To test: go to home, start typing into search, click on a route from autocomplete dropdown
=> Fix route link on search autocomplete to use slug instead of id.

src/app/pages/crags/crags.query.graphql
After areas upgrade, the areas resolver on country entitiy takes a "hasCrags" param.  This is a fix that sets the new param to true in crags list query.
To test, open slovenia and see that only 10 areas are loaded in the TOC.
=> only load areas with crags in crag list view

src/app/common/activity.constants.ts, src/app/forms/activity-form/activity-form-route/activity-form-route.component.html, src/app/forms/activity-form/activity-form-route/activity-form-route.component.ts, src/app/forms/activity-form/activity-form.component.ts, src/app/pages/crag/crag-by-slug.query.graphql, src/app/shared/components/grade-select/grade-select.component.html, src/app/shared/components/grade-select/grade-select.component.ts, src/app/shared/services/grading-systems.service.ts
closes #121 
Sends user's vote on difficulty of a route when a user logs a route.
Test this by logging a route. Then check db if difficultyVote is added and check the route if difficulty is adjusted. 
You can try finding a route with such previous votes that your vote will change the grade.
Should discuss again about how to handle voting and private logs. Now for private logs (only for private) the vote control is simply disabled on FE.
Should probably add constraint ob BE or let users vote anyway and display such votes as anonymous. 
But I suggest that we keep all votes public and that privacy only affects the actual log.  Maybe we only need to clarify this to the user somehow...
=> Difficulty votes

src/app/pages/crag/crag-location/crag-location.component.html
Hide map on crag view if coordinates are not defined. Hide orientation row if no orientation is defined.
Test by going to a crag with no coordinates (e.g. Nomenj)
and by going to a crag with no orientation (e.g. Bitenj potok).
closes #126
=> Hide map and/or coordinates on crag view if not defined.

src/app/pages/crags/crags.component.html, src/app/pages/crags/crags.component.scss
When map is shown above crags list (Slovenia) all is good.
When map is not shown above crags list (all other countries) margin was missing.
=> Fix minor layout issue on map above crags list.

src/app/pages/crag/crag-by-slug.query.graphql, src/app/pages/crag/crag-routes/crag-routes.component.html
For sectors that have only boulders, do not display height column at all. 
For mixed sectors, just do not display height in the boulder row.
To test this:
First pull BE branch with same name.
Open for example PCL crag which has both boulders and sport routes to see the sector without height column.
Then change routeTypeId of some routes in db to get a 'mixed' sector.
=> Hide height on boulders

src/app/forms/club-member-form/club-member-form.component.ts, src/app/pages/club/club-activity-routes/club-activity-routes.component.ts, src/app/pages/club/club-members/club-members.component.ts
Test this by identifying the bug on master first, which is:
Go to clubs, club, activity routes tab.
Go back to members tab.
Add or remove a member. 
Go back to activity-routes tab. 
Activity-routes list should have updated by removing ars of the deleted member or adding ars of the added member, but doesn't 
Switch to this branch and try again. Should work now.
=> Fix cache bug on clubs.

src/app/forms/activity-form/activity-form.component.html, src/app/forms/activity-form/activity-form.component.scss, src/app/forms/activity-form/activity-form.component.ts
When logging routes one could log a route with custom name. 
Removed this option now. 
Test by trying to log a custom route, which is not possible anymore. :)
closes #107
=> Remove custom route in activity

src/app/forms/activity-form/activity-form.component.ts, src/app/pages/activity/activity-input/activity-input.component.html, src/app/pages/activity/activity-input/activity-input.component.ts
After submitting a log, user can navigate back via back button.
But there are no routes to log in local storage anymore.
Displays message.
test> Log a route. Click browser back button.
closes #105 
closes #122
=> Empty route list on log form

src/app/pages/crags/crags.component.html, src/app/shared/pipes/orientation.pipe.ts
Fixed layout on crags list view to accommodate enough space for orientation strings.
Also modified orientation pipe to accept a parameter. It was not used in the end for this issue, but might come in handy later, so left it anyway...
test this by going to crags list page and narrowing the browser window and observing the layout.
closes #139
=> Fix orientation overflowing

src/app/graphql/routes/route-comments.query.graphql
The `<app-comment>` component that is used in different places is expecting the user object to have a `fullName` property. The query used by the route preview component provided `firstname` and `lastname` but not the `fullName`.
Before:
After:
=> Fix bug where comment author was missing in route preview

src/app/pages/home/latest-images/latest-image.query.graphql, src/app/pages/home/popular-crags/popular-crags.query.graphql, src/app/pages/search/search-results/search.query.graphql, src/app/pages/search/search.component.html, src/app/pages/search/search.component.ts, src/app/pages/search/searchAutoComplete.query.graphql
When searching now all entities except comments are searched within the autocomplete. If search string is confirmed the search results page is still displayed and all entities (including comments) are searched.
To test try searching for a term that should appear in comments and see that autocomplete does not display results of type comments. Confirm search and see that comments are then still searched and shown on results page.
closes #187
=> Search no comments in autocomplete

src/app/pages/route/route-comments/route-comments.component.html, src/app/pages/route/route-comments/route-comments.component.ts, src/app/pages/route/route.component.html, src/app/pages/route/route.component.ts, src/app/shared/components/comment-form/comment-form.component.ts
Makes 'Dodaj komentar' button on route work.
It also displays all types of comments on route page, even if the list is empty. 
Fixes some nested subscriptions and error handling.
Test this by adding comments of different types to a route.
closes #191
=> Comments on route fix

src/app/pages/crags/crags.query.graphql
This can be merged at any time, before it is, I might add some minor optimisations to queries.
For example in crags view, country was loaded with a subquery (which you can get from parent). 260ms -> 100ms
=> Performance optimization

src/app/services/local-storage.service.ts
Two bugs are fixed with this PR:
1. Auth token has no expirationDate.  LocalStorageService now expects that possibility when getting an item.
2. If a token (item) is expired then it is now properly removed. (Was being "double prefixed" before)
Test by refreshing the page multiple times while being logged in.
closes #198
=> Fix auth token check

src/app/common/distribution-chart/distribution-chart.component.html, src/app/common/distribution-chart/distribution-chart.component.scss, src/app/common/distribution-chart/distribution-chart.component.ts, src/app/pages/route/route-info/route-info.component.html, src/app/pages/route/route-info/route-info.component.scss, src/app/shared/services/grade-distribution.service.ts
Fixes in this PR:
1. fixes misaligned bars in chart when label is long (e.g.: 6c+/7a) https://github.com/plezanje-net/web/issues/184
2. fixes distribution calculation bug where all bars were showing 100%
3. add spacing between distribution chart and difficulty votes list
All three issues are seen on these examples:
Before:
After:
=> Diff votes chart fixes

src/app/pages/crags/crags.component.ts, src/index.html
- Loads openlayers so it wont block page render (you can see the difference in lighthouse report)
- Adds crag type param to crag list request so it wont show alpine crags (test with api pr https://github.com/plezanje-net/api/pull/89)
=> Lighthouse & more

src/app/common/image-full/image-full.component.html, src/app/pages/crag/crag-gallery/crag-gallery.component.html, src/app/pages/crag/crag-image/crag-image.component.html, src/app/pages/home/latest-images/latest-images.component.html, src/app/pages/home/latest-images/latest-images.component.ts, src/environments/environment.ts
Using srcset for images, so that the browser can choose correct size based on current screen size. 
keeping src as a fallback.
see image sizes gdrive doc for size calc explanations.
This will of course change when we change the layout. 
Additional sizes of images will probably need to be added based on FE needs.
could probably convert img with srcset to a component to make code cleaner -> another task
could add webp format as default and jpeg as a fallback -> another task
(Some images might not load yet because they have not been uploaded to the server yet... doing this in meantime...)
To test this open network tab in dev tools, resize window so that only a small image is needed. reload page. see that the small image is fetched. resize window so that the image gets bigger. see that the …
=> Added srcset to img tags for more efficient image loading.

src/app/pages/account/confirm-account/confirm-account.component.ts, src/app/pages/account/confirm-account/confirm-account.mutation.graphql, src/app/pages/account/register/register.component.html, src/app/pages/account/register/register.component.ts, src/app/pages/account/select-password/select-password.component.ts, src/app/pages/account/select-password/select-password.mutation.graphql
Redirects to home after user logs in on registration, activation or password reset page. 
(These views are not supposed to be seen by a logged in user.)
Also some minor cleanup:
- moves some gql mutations to .graphql files, 
- fixes a nested subscription
- replaces deprecated observers signatures
Test by going through the process of:
- registering as a new user,
- password reset
and see that everything still works. 
Try logging in on each of the views presented.
closes #264 
(note: could not replicate infinite spinner, so that might have been a false bug report...)
=> Registration fix

src/app/pages/search/search-results/search-results.component.html, src/app/pages/search/search-results/search-results.component.ts, src/app/pages/search/search-results/search.query.graphql, src/app/pages/search/search.component.html, src/app/pages/search/searchAutoComplete.query.graphql
Search does not search for users anymore.
(user links are not working yet, because user profile page does not exist yet).
Test by searching for a user. Observe that the user is not displayed in search autocomplete nor on search results page.
closes #271
=> Disable searching for users.

src/app/common/image-full/image-full.component.html, src/app/pages/crag/crag-gallery/crag-gallery.component.html, src/app/pages/crag/crag-gallery/crag-gallery.component.scss, src/app/pages/crag/crag-image/crag-image.component.html, src/app/pages/crag/crag-image/crag-image.component.scss, src/app/pages/home/latest-images/latest-images.component.html, src/app/pages/home/latest-images/latest-images.component.scss, src/app/shared/components/responsive-image/responsive-image.component.html, src/app/shared/components/responsive-image/responsive-image.component.scss, src/app/shared/components/responsive-image/responsive-image.component.ts, src/app/shared/shared.module.ts
Images are now displayed in relevant sizes (chosen by browser via srcset) and using next gen formats with fallbacks. 
avif->webp->jpeg
To test this might wait until all images in these formats are processed and uploaded to server.
Also can wait for BE migration that will remove image filename extensions from filepaths in db.
If you want to test now, try with images (already uploaded):
-misja-pec
-geyikbayiri-wild-horses
and localy delete their .jpg extension in path in db.
(note: fulsize image popup layout is broken. will be fixed with another issue)
closes #276
=> Add component that can generate a picture tag

src/app/common/image-full/image-full.component.html, src/app/common/image-full/image-full.component.scss, src/app/shared/components/responsive-image/responsive-image.component.scss
Prevents bug where image is larger than 90vh/% which causes the description text to overlap the image.
=> Limit height of picture in gallery

package-lock.json, package.json, src/app/app.module.ts, src/app/graphql/graphql.module.ts, src/app/pages/crags/crags.component.ts, src/environments/environment.prod.ts, src/environments/environment.ts, src/main.ts
This will setup sentry to track frontend errors and enable tracing, to measure performance (so we can find bottlenecks).
Testing:
- log into sentry.io with makeplezanje google account and go to issues: https://sentry.io/organizations/plezanjenet/issues/?project=6291581
- change production environment api url so it points to localhost:3000, but shut down api server
- run "ng serve -c production" and open the browser (should see an error)
- run the api and open an invalid country/crag slug
- check the sentry for those two (or similar) errors
=> Sentry setup

src/app/pages/home/latest-ticks/latest-ticks.component.html
User profile page does not exist yet, so links to it fail. 
Removing links.
To test go to homepage and see that users are displayed as text only.
=> Remove links to user profiles on home.

src/app/auth/auth.service.ts
This PR fixes a bug, which can be reproduced as follows:
1. Log in
2. Go to log, and delete any activity entry
3. Logout
4. Log in again
5. Observe that you get stuck with infinite spinner and that you get an  uncaught auth error in the console.
Reason:
When logging in we were calling resetStore which deletes apollo cache and also refetches queries. Refetching queries caused auth error which was not caught.
Solution:
Use clearStore which only deletes cache.
Try above procedure again and see that it works now.
=> Do not refetch queries on login.

src/app/graphql/graphql.module.ts
Adding retry mechanism to apollo client. On server error (for example when api is getting deployed) it will try 5 times before resulting in error, starting with 500ms delay.
To test this, open a crag, turn off api, refresh and turn on api. You will see a few failed requests in network, depending on how quick you switched the api back on :)
This should be deployed before any api PR.
=> Graphql retry link

src/app/pages/club/club-activity-routes/club-activity-routes.component.html, src/app/pages/club/club-activity-routes/club-activity-routes.component.scss, src/styles/global.scss
issue: https://github.com/plezanje-net/api/issues/101
Fixes the layout on small screen sizes for the club activity routes log.
Example of broken layout:
Example of fixed layout:
https://user-images.githubusercontent.com/6022408/161835739-20bfad13-7704-4e1b-8ee9-ad2cdc080298.mp4
I also reduced the gap between the input fields for sorting. Previously it was 8px, now it's 16px (the same as in activity log or activity form).
=> #101 fix mobile layout of club log for the table and filters

src/app/activity/forms/activity-form/activity-form-route/activity-form-route.component.html, src/app/activity/forms/activity-form/activity-form-route/activity-form-route.component.ts, src/app/activity/forms/activity-form/activity-form.component.ts, src/app/activity/forms/activity-form/activity-form.service.ts, src/app/shared/components/grade-select/grade-select.component.html, src/app/shared/components/grade-select/grade-select.component.ts
1
Fixes disabling difficulty vote when changing visibility
To test this: 
Log a route or many routes and try out different ascent type and publish type selections, changing them in different order. 
Observe that difficulty vote gets disabled as it should now. 
There is one thing to consider though: what are publish types that let user cast a vote? Now they are set up to be: 'public' and 'log'. What is 'log' pt anyway?
This might all be unimportant if we decide to let the user vote in all publish types...
closes #330
2
Fixes resetting ascentTypes on date change. Now keeps them as first set.
To test this:
Start logging some routes. Set ascent types. Change the date. Observe that the selected ascentTypes only change if the date change made them impossible.
Try also projects, and multiple …
=> Fix diff vote disabled visibility bug & more

src/app/activity/forms/activity-form/activity-form-route/activity-form-route.component.html, src/app/activity/forms/activity-form/activity-form-route/activity-form-route.component.ts, src/app/activity/forms/activity-form/activity-form.component.html, src/app/activity/forms/activity-form/activity-form.component.scss, src/app/activity/forms/activity-form/activity-form.service.ts, src/app/pages/changelog/changelog.component.html, src/app/shared/components/grade-select/grade-select.component.ts
1.
Make voting on route difficulty possible on all ascent types (also on non-public ascents).
Test: Try logging a route, choose publish type 'private'. Observe that voting on difficulty is possible.
2.
Fix a bug on mat-select-trigger.
Test: First observe the bug on master: start logging a route, choose ascent type e.g. 'repeat', duplicate the route and see that ascent type is not filled in although it is possible and should be copied from original. Switch to this branch and see that the same works now.
3.
Minor change in difficulty vote input behaviour. It is set to 'scroll' into view only when no difficulty is selected.
Test: Start logging a route. Open difficulty vote input and see that the input 'scrolls' to current route difficulty. Choose some difficulty. Open the input again and …
=> Votes on all logs possible

src/app/pages/home/home.component.html
I suggest we hide this from homepage for now and reenable it when image upload is finished. 
To test: open homepage :)
=> Hide latest images on homepage until image upload is implemented.

src/app/common/sortable-header-field/sortable-header-field.component.scss, src/app/pages/crag/crag-routes/crag-routes.component.scss, src/app/shared/components/ascent-type/ascent-type.component.html, src/app/shared/components/ascent-type/ascent-type.component.scss
Styles in route list had some ng-deep which was making styles spill to other components...
To test> 
on master see the problem by navigating to route list and observe the avatar icon in header becoming too small.
on this branch see that the problem is fixed
=> Fix icon styles spilling from route list.

src/app/activity/forms/activity-form/activity-form-route/activity-form-route.component.html, src/app/activity/pages/activity-routes/activity-routes.component.ts, src/app/activity/partials/activity-entry-routes/activity-entry-routes.component.html, src/app/activity/partials/activity-entry-routes/activity-entry-routes.component.scss, src/app/activity/partials/activity-entry-routes/activity-entry-routes.component.ts, src/app/activity/partials/activity-route-row/activity-route-row.component.html, src/app/activity/partials/activity-route-row/activity-route-row.component.ts, src/styles/global.scss
closes #380 
also closes #363 by making the table scrollable (should rework design of wide tables to avoid horizontal scrolls in a later task)
=> Show user's private activity routes notes on log.

src/app/common/image-full/image-full.component.html, src/app/common/image-full/image-full.component.scss, src/app/common/image-full/image-full.component.ts, src/app/pages/crag/crag-by-slug.query.graphql, src/app/pages/crag/crag-gallery/crag-gallery.component.html, src/app/pages/crag/crag-gallery/crag-gallery.component.ts, src/app/pages/crag/crag-image/crag-image.component.html, src/app/pages/home/latest-images/latest-image.query.graphql, src/app/pages/home/latest-images/latest-images.component.html, src/app/pages/home/latest-images/latest-images.component.scss, src/app/pages/home/latest-images/latest-images.component.ts, src/app/shared/components/responsive-image/responsive-image.component.scss, src/app/shared/components/responsive-image/responsive-image.component.ts
If PR https://github.com/plezanje-net/web/pull/369 is merged before this, make sure that you uncomment latest-images component on homepage before testing.
Test this with: https://github.com/plezanje-net/api/pull/104
Full page view of images is now fixed.
To test this, click through different images, then resize browser window to see that they are always correctly displayed, which is:
- Take up as much space as possible, leaving space for close/prev/next buttons and for caption at the bottom.
- Never upscale the image. 
- Image+Caption should be centred vertically and horizontally.
(If you'd like to easily inspect the layout, you can uncomment the coloured backgrounds from image-full-component.scss)
Also click through other image instances on the page to see nothing else broke. :) 
Buttons …
=> Responsive image update

src/app/management/forms/route-form/route-form.component.html, src/app/management/forms/route-form/route-form.component.ts, src/app/management/pages/crag-sector-routes/management-get-sector.query.graphql, src/app/pages/route/route-grades/route-grades.component.html
Project checkbox and base difficulty fields are left on the form always, but disabled when not editable.
To test try many combinations -> only routes with no user diff votes should have editable base difficulties.
There is a slight inconvenience on editing routes with legacy 'half' base difficulties.
Discussion on how to tackle this is ongoing,...
test with https://github.com/plezanje-net/api/pull/119
also closes #338
=> Enable editing base difficulty on routes with base diff vote only.

src/app/app-routing.module.ts, src/app/app.component.ts, src/app/pages/crag/crag-routes/crag-routes.component.ts, src/app/pages/crag/crag.component.ts, src/app/pages/crags/crags.component.ts, src/app/services/scroll.service.ts
To test this out go to a crag, navigate to a route, then click browser back button. scroll position should be restored.
Thoroughly test by clicking back forward multiple times...
It should work on: 
- routes list
- crags list
closes #355
=> Basic scroll restoration logic added and used on crags and crag pages.

src/app/auth/login/login.component.html, src/app/auth/password-recovery/password-recovery.component.html, src/app/pages/account/register/register.component.html
changing html types from text to email disables autocapitalise on mobile
tested on xcode's iphone simulator
bonus for issue https://github.com/plezanje-net/api/issues/117
=> set html type on email inputs

src/app/pages/crag/crag-routes/crag-routes.component.ts, src/app/pages/crags/crags.component.ts, src/app/pages/search/search-results/search-results.component.html, src/app/pages/search/search-results/search-results.component.ts, src/app/pages/search/search-results/search.query.graphql, src/app/pages/search/search.component.ts, src/app/pages/search/searchAutoComplete.query.graphql, src/app/shared/services/search.service.ts
Search yields entities that are mostly sport but might also be of type alpine. 
Alpine routes have own routing under Alpinism and links on search are now properly generated.
To test:
try searching for all the different entity types (crag, sector, route, comment), and for each of them find an example of 'sport' and an example of 'alpine' type.
Determine that all links to these entities are properly generated.
'Internal' search was not working because it did not unaccent characters. Fixes this for most cases. 
To test:
try opening a crag with some routes that have accents in names. eg. smwh in Spain or France.
Se that unaccented characters work for searching for accented characters.
closes #406 
closes #408 
test with https://github.com/plezanje-net/api/pull/128
=> Fix search

src/app/common/map/map.component.html, src/app/common/map/map.component.scss, src/app/common/map/map.component.ts, src/app/pages/home/latest-difficulty-votes/latest-difficulty-votes.component.ts
Diff votes on home now use the common loader and subscribe to auth service, to update results upon login/logout.
For testing (if it does not happen on its own), you can add timeout (see what was removed in the second commit).
closes #412 
Other:
- adds overlay to map until clicked on, so it wont scroll the map on mobile until it is interacted with (long overdue)
=> #412 Home difficulty votes loader + more

src/app/activity/forms/activity-form/activity-form-route/activity-form-route.component.html, src/app/activity/forms/activity-form/activity-form-route/activity-form-route.component.scss, src/app/activity/forms/activity-form/activity-form.component.ts, src/app/activity/forms/activity-form/activity-form.service.ts, src/app/activity/forms/activity-form/star-rating-votes.query.graphql, src/app/activity/pages/activity-routes/activity-routes.component.ts, src/app/pages/crag/crag-by-slug.query.graphql, src/app/pages/crag/crag-routes/crag-routes.component.html, src/app/pages/crag/crag-routes/crag-routes.component.ts, src/app/shared/pipes/genderize-verb.pipe.ts, src/app/shared/pipes/pluralize-noun.pipe.ts, src/styles/global.scss
a.
~~Hides stars from route list unless at least N star ratings are cast. N is set to 3 now. Seems better/ok now, but might discuss this and alter this constant.~~
I vote for making it even more conservative or leaving it as is. I believe stars should be used sparingly and shown on routes where there really is a somewhat 'wide' consensus on the route's beauty.
But...
this may only postpone the same problem we have now... (to many routes with stars).
I fear that we will eventually come to all routes having some votes and most of them will average out to 1 star...
Maybe consider another way of determining stars shown?
only show stars if one of the possible starRatings has some predefined majority?
eg.:
0stars: 100 votes
1star: 100 votes
2stars: 100 votes
would now show one star
but if we …
=> 383 star rating calcs update

src/app/pages/crag/crag-info/crag-info.component.html, src/app/pages/crag/crag-info/crag-info.component.ts, src/app/pages/route/route-info/route-info.component.html, src/app/pages/route/route-info/route-info.component.ts
To test - test the buttons in crag and route info that appear only for logged in users.
The long term idea is to display last few ascents / activities with the link and to hide this if there is no history with this crag/route. 
This will probably be addressed after the FE rework and is not part of this PR.
=> Open filtered log from crag and route page

src/app/common/image-full/delete-image.mutation.graphql, src/app/common/image-full/image-full.component.html, src/app/common/image-full/image-full.component.scss, src/app/common/image-full/image-full.component.ts, src/app/pages/crag/crag-by-slug.query.graphql, src/app/pages/route/route.query.graphql
#438 
This PR adds the option to delete an image. This can only be done by the user that uploaded the image.
Example of dialog before deleting. Notice the trash icon button in the top right corner.
Test with the [matching api PR](https://github.com/plezanje-net/api/pull/148).
=> #438 Add option to delete an image

src/app/pages/club/club-activity-routes/club-activity-routes.component.ts, src/app/pages/club/club-activity-routes/user-full-name.query.graphql
User query on BE was a bit leaky...
since only club area was using it, club logic was refactored so that it doesn't need it anymore.
test with: https://github.com/plezanje-net/api/pull/159
=> Don't use user gql query

src/app/management/forms/route-form/route-form.component.ts
A route with no ascents should let admins edit it's grade.
nrTries can be null as it seems and in this case the condition ==0 is wrong.
should also check api why
=> Fix bug where a route' base grade cannot be edited
